base_url = "https://fassbender.dev/blog"
title = "Jonas' Blog"
description = "Something profound"

compile_sass = true

build_search_index = false

theme = "anatole-zola"

taxonomies = [
  {name = "tags"},
]

default_language = "en"

[languages.en.translations]
language_name = "English"
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"

[markdown]
highlight_code = true

[extra]
share = false
back_button = false

[extra.show]
tags = true
links = true

[extra.social]
homepage = "https://fassbender.dev"
github = "jofas"
stackoverflow = "20665825"
linkedin = "jofas"
